platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'JSONModel'
pod 'Facebook-iOS-SDK', '~> 3.15.1'
pod 'SVProgressHUD', :head
pod 'MJPopupViewController', '~> 0.4'
pod 'MLPAccessoryBadge'
pod 'MSPullToRefreshController', '~> 1.1.0'
pod 'pop', '~> 1.0'
pod 'SDWebImage'
pod 'WYPopoverController', '~> 0.2.0'
pod 'Parse'